name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install foreman
        uses: rojo-rbx/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: ls
        run: ls
      - name: install foreman packages (rojo, run-in-roblox)
        run: foreman install
      - name: run rojo build
        run: rojo build -o test.rbxlx
      - name: run tests
        run: run-in-roblox --place test.rbxlx --script .\\RunPractTest.server.lua
