name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: download roblox install script
        run: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/OrbitalOwen/roblox-win-installer/master/install.py" -OutFile install.py
      - name: download settings file
        run: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/OrbitalOwen/roblox-win-installer/master/GlobalSettings_13.xml" -OutFile GlobalSettings_13.xml
      - name: install pip deps
        run: pip install wget psutil
      - name: install roblox
        run: python install.py "${{ secrets.ROBLOSECURITY }}"
      - name: install foreman
        uses: rojo-rbx/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: install foreman packages (rojo, run-in-roblox)
        run: foreman install
      - name: run rojo build
        run: rojo build -o test.rbxlx
      - name: ls
        run: ls
      - name: run tests
        run: run-in-roblox --place test.rbxlx --script RunPractTest.server.lua
